CREATE TABLE Users
(
	Id SERIAL PRIMARY KEY,
	Username VARCHAR(60) UNIQUE,
	User_role VARCHAR(60),
	Email VARCHAR(255) UNIQUE,
	User_password VARCHAR(255)
);

CREATE TABLE Orders
(
	Id SERIAL PRIMARY KEY,
	Title VARCHAR(90),
	CustomerId INTEGER,
	Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Task_type VARCHAR(60),
	Status VARCHAR(60),
	Description TEXT,
	FOREIGN KEY (CustomerId) REFERENCES Users (Id)
);

CREATE TABLE DataItems
(
	Id SERIAL PRIMARY KEY,
	OrderId INTEGER,
	Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	File_path TEXT,
	FOREIGN KEY (OrderId) REFERENCES Orders (Id)
);

CREATE TABLE Labels
(
	Id SERIAL PRIMARY KEY,
	WorkerId INTEGER,
	DataItemId INTEGER,
	Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	LabelType VARCHAR(60),
	FOREIGN KEY (WorkerId) REFERENCES Users (Id),
	FOREIGN KEY (DataItemId) REFERENCES DataItems (Id)
);

CREATE TABLE BoundingBoxes
(
	Id SERIAL PRIMARY KEY,
	LabelId INTEGER,
	DefClass VARCHAR(60),
	X_Max DOUBLE PRECISION,
	Y_Max DOUBLE PRECISION,
	X_Min DOUBLE PRECISION,
	Y_Min DOUBLE PRECISION,
	FOREIGN KEY (LabelId) REFERENCES Labels (Id)
);

CREATE TABLE ClassificationLabels
(
	Id SERIAL PRIMARY KEY,
	ClassName VARCHAR(60),
	LabelId INTEGER,
	FOREIGN KEY (LabelId) REFERENCES Labels (Id)
);